"""added_jwt_token_models

Revision ID: 5ef7b0308b5a
Revises: 193381dfcd84
Create Date: 2024-12-14 21:46:09.847606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ef7b0308b5a"
down_revision: Union[str, None] = "193381dfcd84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assigned_jwt_access_token",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("jti", sa.UUID(), nullable=False, comment="Идентификатор токена"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен"),
        sa.Column("expired_time", sa.DateTime(timezone=True), nullable=False, comment="Окончание доступа"),
        sa.Column("device_id", sa.String(length=100), nullable=False, comment="Устройство пользователя"),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_assigned_jwt_access_token_jti"),
        "assigned_jwt_access_token",
        ["jti"],
        unique=True,
    )
    op.create_table(
        "assigned_jwt_refresh_token",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("jti", sa.UUID(), nullable=False, comment="Идентификатор токена"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен"),
        sa.Column("expired_time", sa.DateTime(timezone=True), nullable=False, comment="Окончание доступа"),
        sa.Column("device_id", sa.String(length=100), nullable=False, comment="Устройство пользователя"),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_assigned_jwt_refresh_token_jti"),
        "assigned_jwt_refresh_token",
        ["jti"],
        unique=True,
    )
    op.alter_column(
        "user",
        "is_superuser",
        existing_type=sa.BOOLEAN(),
        comment="Суперпользователь",
        existing_comment="супер пользователь",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "is_staff",
        existing_type=sa.BOOLEAN(),
        comment="Персонал",
        existing_comment="супер пользователь",
        existing_nullable=False,
    )
    op.create_unique_constraint("user_id_key", "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_id_key", "user", type_="unique")
    op.alter_column(
        "user",
        "is_staff",
        existing_type=sa.BOOLEAN(),
        comment="супер пользователь",
        existing_comment="Персонал",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "is_superuser",
        existing_type=sa.BOOLEAN(),
        comment="супер пользователь",
        existing_comment="Суперпользователь",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_assigned_jwt_refresh_token_jti"),
        table_name="assigned_jwt_refresh_token",
    )
    op.drop_table("assigned_jwt_refresh_token")
    op.drop_index(
        op.f("ix_assigned_jwt_access_token_jti"),
        table_name="assigned_jwt_access_token",
    )
    op.drop_table("assigned_jwt_access_token")
    # ### end Alembic commands ###
